import React, { Fragment } from 'react'
import { Honeycomb, Navbar, } from './sections'


const CanvasPrime = () => 
    <Fragment>
        <Honeycomb />

        <div 
            style={{ height: '500vh',
                width: '100vw',
                //paddingTop: '60vh',
                background: '#05090A', }} >

            <Navbar />

            <p style={{ color: '#fff', fontSize: '2rem', padding: '60vh 4rem', }} >Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum iaculis lectus nec nibh maximus facilisis. Vestibulum id leo non tortor vestibulum iaculis laoreet quis mi. Duis tincidunt justo vitae arcu scelerisque, vehicula tempor purus pharetra. Morbi dui dolor, aliquam sit amet tortor in, venenatis tincidunt metus. Nunc justo enim, elementum in urna non, varius dapibus nulla. Quisque ultricies tellus vitae purus elementum lobortis. Ut vehicula est in tellus molestie dictum. In hac habitasse platea dictumst. Aliquam semper fringilla ex eleifend pulvinar. Curabitur at congue eros. Sed iaculis posuere neque in viverra. Suspendisse in tincidunt libero. Donec molestie magna nisl, vitae gravida ligula vehicula ut. Pellentesque ut placerat lectus. Sed leo ex, congue quis justo sit amet, tempor bibendum lectus. Mauris orci tellus, consequat ut sollicitudin eu, semper id quam.

            Ut luctus, leo nec consectetur varius, sapien dolor accumsan neque, maximus pretium felis justo vestibulum turpis. Suspendisse potenti. Aenean sed aliquam diam. Integer id fringilla mauris, eu dignissim ligula. Quisque ligula velit, ullamcorper sit amet commodo eget, dictum quis magna. Donec egestas velit eget elit posuere, nec blandit lorem venenatis. Integer accumsan tellus nec felis consectetur, vulputate dignissim velit semper. Quisque nisl odio, rutrum sed mattis vitae, fringilla non mauris. Morbi accumsan condimentum erat id fringilla. Curabitur efficitur dui eget elit ultricies tincidunt. Proin sit amet placerat leo, vel facilisis mauris. Duis congue vitae nisl sit amet imperdiet.
            
            Quisque euismod elementum lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec at rutrum metus, tempus pulvinar lectus. Duis id accumsan est. Sed non leo urna. Fusce sed malesuada sapien. Etiam in accumsan ante. Nullam porta lorem purus, a tincidunt leo ultricies ut. In sed aliquam ligula. Nunc pulvinar nulla et eros venenatis ultrices. Vivamus vitae fermentum nibh.
            
            Nulla semper est eget turpis vulputate porta. Duis aliquet at nisi et dictum. Phasellus eu nisl at nibh efficitur auctor quis sed leo. Maecenas porta tortor sit amet lorem hendrerit, sit amet fermentum ex facilisis. Donec eu vehicula mauris, nec tempus ex. Donec purus arcu, accumsan vel velit viverra, ultricies euismod velit. Sed sed turpis aliquam, feugiat nisi ut, dapibus tortor. Donec accumsan sapien sem, ac pharetra mi sollicitudin vel.
            
            Vivamus sed enim dolor. Sed vitae consequat massa. Vestibulum dignissim facilisis sem semper efficitur. Nunc sapien ante, tincidunt at ipsum in, venenatis blandit erat. Integer in convallis ex, quis consequat quam. Cras pellentesque tortor odio. Donec scelerisque odio massa, id varius ipsum tincidunt sagittis. Ut eu lectus mi. Nam odio mauris, consectetur ut pulvinar ut, luctus in sem. Pellentesque tincidunt sem augue, vel elementum ante eleifend ac. Phasellus ex urna, bibendum et dictum at, maximus in est.
            
            Sed tincidunt tortor id elit facilisis porttitor accumsan non tellus. Morbi euismod eros elementum ultricies scelerisque. Aenean bibendum ipsum eget nisl ullamcorper accumsan. Vestibulum ut sem rutrum, luctus orci at, dignissim sapien. Donec felis lorem, tempor et dui at, finibus convallis eros. Proin sagittis viverra justo vel finibus. Duis vitae dui ac odio vulputate finibus. Duis ut elit pellentesque, ornare orci bibendum, sollicitudin eros. Sed sagittis auctor lacus, at cursus metus dignissim vitae. Vivamus dignissim tempor sapien, et ornare nunc consectetur ut. Ut a fringilla est. Aliquam accumsan lorem sit amet dui maximus, ut fermentum augue interdum. Vestibulum dolor massa, venenatis condimentum nunc vel, pulvinar maximus dui. Praesent ut blandit elit, nec ullamcorper ex.
            
            Suspendisse condimentum, nulla vitae blandit tincidunt, lacus lacus dignissim justo, in pretium leo ligula maximus metus. Vestibulum interdum urna in pharetra sagittis. Nunc sed mi cursus enim lacinia lacinia. Aenean finibus, enim non consequat dapibus, est enim tempus magna, eget fringilla elit odio vitae ipsum. Suspendisse mollis sed magna et dapibus. Proin luctus quam lectus, et congue dolor maximus non. Etiam ac pulvinar lectus. Nullam nec augue nec nunc volutpat tristique.
            
            Suspendisse potenti. Aenean dapibus nec massa non efficitur. Etiam at interdum lectus. Duis consequat, orci et rutrum ultricies, erat libero elementum ante, eget fringilla felis nisl tristique tellus. Ut molestie mauris quis tortor vestibulum, vel gravida magna posuere. Sed enim turpis, eleifend mattis diam eget, eleifend feugiat elit. Cras consectetur dictum ligula, vitae semper mi mollis et. Nam consectetur molestie dapibus. Vestibulum posuere id mi sed ornare. Donec vitae massa non mi fringilla condimentum. Aliquam vulputate nisi consequat, auctor enim eu, egestas elit. In finibus varius commodo. Duis cursus id odio non vulputate. Nam leo metus, gravida et suscipit ut, iaculis id lorem. In facilisis quam quis eleifend feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
            
            Suspendisse pulvinar mattis sem in consequat. Vestibulum dui sem, pulvinar id dapibus non, pulvinar sed nunc. Sed ut augue at nisi vulputate placerat. Vivamus sollicitudin dolor vel lacus rhoncus dictum. Mauris eget molestie dui. In vel nibh arcu. Sed est sapien, facilisis ac rutrum in, bibendum at tortor. Quisque iaculis at arcu sodales aliquam. Cras bibendum sodales tellus quis laoreet. Nam consectetur vitae arcu varius aliquam.
            
            Morbi tortor odio, scelerisque eu accumsan in, hendrerit vel nunc. Duis ut justo fringilla, facilisis sapien eget, commodo ante. Sed elementum nisi neque, id porttitor justo venenatis ut. Maecenas nibh tortor, ornare ac magna ultricies, rutrum scelerisque libero. Aliquam erat volutpat. Donec sed hendrerit mauris, quis viverra nulla. Curabitur sit amet purus vulputate sem egestas iaculis. Maecenas placerat quis elit ac luctus. Proin eget nibh sed justo elementum ornare ac ac augue. Pellentesque sodales sed enim eu efficitur. Vivamus et felis lacus.
            
            Phasellus pulvinar lobortis ultrices. Maecenas vulputate lorem quis posuere aliquet. Cras tellus justo, faucibus eu urna sit amet, laoreet tincidunt erat. Ut placerat rhoncus dolor, vitae euismod est viverra ut. Integer faucibus sapien urna, ut interdum magna fringilla ac. Nunc suscipit consequat nisi at aliquet. Quisque leo tellus, ornare sed lorem quis, pellentesque finibus mi. Vivamus eu rhoncus velit, sit amet luctus enim. Nulla facilisis sapien sit amet lacinia suscipit. Curabitur mollis elit in massa consequat facilisis. Aliquam lectus turpis, porta et accumsan vitae, porttitor non justo. Nullam risus purus, consectetur id accumsan nec, hendrerit eget ex. Cras tincidunt dignissim euismod. Praesent a enim id enim tristique porttitor quis et purus. Nulla facilisi. Morbi augue nibh, dignissim sed imperdiet at, posuere ac eros.
            
            Donec quis tincidunt nisl. Maecenas porttitor, dui non volutpat accumsan, metus neque dapibus risus, at pretium leo neque ut tellus. Proin vitae ipsum auctor, eleifend lorem sit amet, ultricies ipsum. Praesent et neque tincidunt, placerat felis ut, pharetra massa. Proin id lacinia quam. Phasellus ut dapibus dolor. Fusce sed est ac urna convallis lobortis. Sed auctor odio tortor, at maximus tellus bibendum sit amet. Phasellus faucibus viverra tellus eget maximus. Ut ut orci leo. Cras ut semper sem.
            
            Sed ac ante augue. Praesent quis lacus neque. Suspendisse laoreet sem ex, eget porttitor nulla egestas eu. Nullam a ligula turpis. Nulla eu nibh sit amet risus faucibus porta non sit amet leo. Fusce a dui rutrum est mollis porttitor quis eu mauris. Maecenas dolor dui, mattis id pellentesque vitae, consequat sed diam. Suspendisse potenti. Nunc placerat malesuada dui eget varius. Mauris auctor elementum ante a tempor. Suspendisse potenti. Cras ultricies vitae quam ut venenatis. Phasellus ac arcu turpis.
            
            Integer non magna at erat fermentum blandit feugiat eu neque. Proin vel ante in nisi dignissim fringilla. Cras turpis magna, hendrerit vel finibus ac, elementum a velit. Donec blandit dapibus diam sed finibus. Phasellus vitae nulla non massa varius egestas nec a ante. Quisque finibus lacus ut hendrerit maximus. Donec viverra sit amet tellus in bibendum. Aliquam in ipsum ac ipsum porttitor rhoncus ut non turpis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aenean malesuada commodo aliquam. Donec et magna nisi. Suspendisse nec turpis sit amet leo aliquet mollis. Nam eget varius eros, quis egestas turpis. Nam dictum elit tellus, at aliquet mauris ornare vel. Nam ultrices ex dapibus, lobortis diam sit amet, tempus ipsum.
            
            Cras nec elit semper, gravida orci id, rhoncus nunc. Nunc luctus mollis nibh ornare vestibulum. Nulla tempus fringilla ultrices. Ut interdum, orci dapibus scelerisque pellentesque, quam lacus aliquet felis, sit amet imperdiet enim arcu ac metus. Nullam ultrices quam tortor, vitae iaculis orci facilisis efficitur. Aenean id laoreet nisi. Etiam eu risus nec urna euismod placerat. Aenean et felis sit amet libero sollicitudin condimentum non quis lectus. Vivamus nunc nibh, egestas nec consectetur vel, imperdiet ac nisi. Quisque libero sapien, sollicitudin in velit ut, scelerisque elementum ipsum. Nam sodales auctor nunc, quis semper diam rhoncus nec. In hac habitasse platea dictumst.
            
            Phasellus non viverra tortor. Ut placerat ullamcorper fringilla. Maecenas ac ultricies risus. Cras eleifend purus quis imperdiet commodo. Nam consectetur a quam condimentum tincidunt. Pellentesque luctus euismod lectus, eu ornare libero blandit et. Proin eget quam ut mi viverra eleifend non vitae dui. Nulla facilisi. Nulla cursus turpis nec vestibulum fringilla. Morbi rhoncus tincidunt est vel sollicitudin. Sed non velit sed dolor condimentum consequat. Aliquam nec tristique purus. Donec eu enim non velit feugiat pellentesque. Curabitur quam lectus, ullamcorper in luctus tempor, consequat sed velit. Etiam id sem at odio facilisis imperdiet.
            
            Curabitur at nisi et mi volutpat viverra. Sed lacus arcu, porttitor ac orci ac, bibendum dapibus mauris. Vestibulum in libero vitae sapien scelerisque accumsan sit amet finibus diam. Sed ut ligula ac ante imperdiet vulputate. Etiam quis lacus sit amet sapien aliquam lobortis vel sit amet purus. Vivamus erat mi, mattis id felis ut, posuere malesuada risus. Sed tincidunt felis et justo ultricies varius gravida at tortor. Sed tincidunt arcu quis sem semper, pharetra egestas erat posuere. Praesent vulputate diam vel dolor luctus, vitae mollis risus iaculis. Duis a sem ut augue lacinia malesuada vel et ante. Sed ante turpis, hendrerit ac egestas at, venenatis ut arcu. Maecenas posuere varius convallis. Aliquam sed blandit justo.
            
            Quisque semper lacus vitae risus consequat mattis. Curabitur ut suscipit lectus, at vehicula eros. Donec et tortor vitae diam auctor cursus ut a ante. Sed sem est, egestas eu aliquet sed, facilisis nec massa. Nullam nec lobortis augue. Integer lacus neque, sollicitudin sed lectus vel, molestie pretium enim. Morbi ac mi elementum, tempus dui vel, interdum leo. Aliquam tristique risus nec hendrerit sodales. Donec ipsum nibh, sollicitudin quis efficitur quis, iaculis volutpat tortor. Sed at venenatis mi. Aenean ultricies, magna a aliquam convallis, mauris augue vehicula quam, eu sagittis dui eros non diam. Ut tristique lobortis enim id ultricies. Sed a purus eget libero sodales hendrerit non ut diam. Phasellus arcu purus, posuere ullamcorper nulla nec, imperdiet feugiat quam.
            
            Duis vel ex massa. Integer non rhoncus justo, id sollicitudin urna. In rhoncus ligula vel condimentum dignissim. Morbi consectetur, dolor ut interdum pulvinar, elit neque aliquam velit, nec dictum turpis nisl at urna. Aliquam dapibus, nulla non dignissim hendrerit, nisi justo elementum odio, sed convallis odio sapien id velit. Nam placerat libero est, quis sagittis dolor vulputate et. Sed faucibus blandit feugiat. Ut sit amet urna eu neque cursus vestibulum ut sit amet tellus.
            
            Etiam venenatis faucibus libero, in consectetur velit sodales lacinia. Etiam malesuada ultricies mi, at vulputate nulla tincidunt vel. Pellentesque viverra velit ut consectetur mattis. Donec scelerisque fringilla mauris in pretium. Cras tortor purus, sagittis at tortor et, lobortis posuere erat. Etiam vestibulum quam lacus, gravida luctus tellus sagittis ut. Sed sit amet magna nec nisl iaculis mattis. Maecenas placerat eros at mi porttitor efficitur. Fusce ornare porttitor eleifend. Ut congue, neque sit amet varius congue, nunc libero volutpat ipsum, a dictum est arcu ut leo. Duis ac felis nec massa ullamcorper consectetur. In hac habitasse platea dictumst. In elementum, elit quis fringilla dictum, orci purus sagittis metus, sit amet scelerisque erat ipsum eu ante. Nam at metus tristique, aliquet augue sit amet, porta lorem. Cras sagittis dapibus lectus, sit amet sollicitudin turpis aliquam ac. Nam aliquet felis sit amet suscipit ultricies.</p>
        </div>

        
    </Fragment>


export default CanvasPrime 
